### ISSUE TITLE
[suggestion] Effect organization

### ISSUE THREAD

**Issue by ZoomTen** [cgvirus/Olive-Editor-Community-Effects#1]
If this repo grows, it would be a little overwhelming if all of the `.xml` and `.frag` files are on the same folder. The user should be able to easily pick and choose the effects they want to add, and I think a good way would be to split effects into different folders.

Downside is that the effect developer will need to refer to `../common.vert` (included with the repo) or `../../common.vert` (incuded with Olive) in their xml files.

Also would the `common.vert` file in the repo be compatible with Olive if a later version updates it? I'm afraid that it might break color or something.

**Comment by cgvirus** [comment]
Some change are made in the structure.. For now, we need to wait for `furtherOCIO` changes for common vert compatibility issue. It will be easy just to replace two files when upgrade is done.
Thanks for suggestion.
If you think this structure is ready you can close the issue.

**Comment by ZoomTen** [comment]
The structure is alright I guess, other than a risk of `common.vert` redundancy. (and possibly it not playing as well with Olive's default effects)

What I meant by compatibility is that there might be something in some newer `shader.frag` that requires changes in the effect codes themselves. As in, drop-in replacements won't be feasible. I believe it's still manageable if the repo still has a few effects by the time `furtherOCIO` is merged in.

Anyway, thanks for implementing my suggestion! Closing for now.
