### ISSUE TITLE
Bloom Shader?

### ISSUE THREAD

**Issue by ghost** [cgvirus/Olive-Editor-Community-Effects#10]
Is it possible to implement a glare shader with parameters such as `threshold`, `radius`, and `intensity`?

Thanks for your work on this, makes Olive more fun to edit :)

**Comment by cgvirus** [comment]
Hi, just added. You can close the issue if it's alright.
https://github.com/cgvirus/Olive-Editor-Community-Effects/tree/master/bloom

**Comment by ghost** [comment]
Perfect thank you 😄
