### ISSUE TITLE
I've made a simple despill effect for green screen

### ISSUE THREAD

**Issue by unfa** [cgvirus/Olive-Editor-Community-Effects#18]
I've coded a simple despill effect for fixing gree nedges on green screen chorma-keyed footage for my own needs.

It lacks any configuration rigth now.

I'd like to make it work for R G or B channels, and allow controlling the influence and other things, but I don't know how to do that yet.

Here's the code:

[despill.tar.gz](https://github.com/cgvirus/Olive-Editor-Community-Effects/files/3124369/despill.tar.gz)

**Comment by unfa** [comment]
I've tried to add an option to choose which channel will be despilled, but for some reason it stopped working.

If you can - please help me fix it.

I don't know how to debug a shader :P

[despill2.tar.gz](https://github.com/cgvirus/Olive-Editor-Community-Effects/files/3124386/despill2.tar.gz)

**Comment by cgvirus** [comment]
It was not working as you have declared same variable r g b twice in the same scope. Here is the modification 
[despill.zip](https://github.com/cgvirus/Olive-Editor-Community-Effects/files/3124410/despill.zip)

**Comment by unfa** [comment]
Yeah, thanks! Someone on Olive Disocrd also pointed this out to me.

**Comment by unfa** [comment]
Anyway - I've submitted a pull request to Olive master.

**Comment by cgvirus** [comment]
Most welcome. Closing the issue then.

**Comment by unfa** [comment]
Thanks! I've learned how to submit PRs for this. I'll probably make more efects in the future.

**Comment by cgvirus** [comment]
If the main Olive branch is busy (it is actually), you can submit your effects here in this community repo as well. I will verify and merge them ASAP. Thanks for the contrib.

**Comment by unfa** [comment]
I'll see, I wouldn't want to duplicate that as it'd only raise confusion.
