### ISSUE TITLE
Olive v0.1.0

### ISSUE THREAD

**Issue by ghost** [cgvirus/Olive-Editor-Community-Effects#19]
Please, add note in the `README.md` that those effects and `frei0r` still supported by *Olive* `v0.1.0` release:

- https://github.com/olive-editor/olive/releases/tag/0.1.0

Details

- https://github.com/olive-editor/olive/issues/767#issuecomment-482963655

**Comment by cgvirus** [comment]
This repo is not dealing with `frei0r`. Other plugs will be ported to updated code base, waiting to be merged with stable release.

**Comment by ghost** [comment]
> This repo is not dealing with `frei0r`

No, I mean that *Olive v0.1.0* is last version that support `frei0r` effects AND current version of `Olive-Editor-Community-Effects`.

So, It would be cool if you create separate branch of community effects for maintaining purpose as:

- https://github.com/cgvirus/Olive-Editor-Community-Effects/tree/v0.1.0
