### ISSUE TITLE
System wide install of Community Effects?

### ISSUE THREAD

**Issue by corestaq** [cgvirus/Olive-Editor-Community-Effects#26]
Hi

Can someone tell me if there is a global system location that I can install the Olive-Editor-Community-Effects instead of in each users home folder?

I have tried /usr/local/share/olive-editor/effects/ and /usr/share/olive-editor/effects/ to no effect

I have built olive from the 0.1.2 release source code and built and running on Aarch64 Linux system (custom OS for Arm TV Box)

**Comment by botfap** [comment]
Fixed

**Comment by corestaq** [comment]
Problem was my makefile setting wrong permissions on install. Community Effects work just fine when placed in /usr/share/olive-editor/effects/ for non snap / flatpak installs
