### ISSUE TITLE
bokehBlur name: "Bookeh Blur" or "Bokeh Blur"?

### ISSUE THREAD

**Issue by ghost** [cgvirus/Olive-Editor-Community-Effects#9]

**Comment by ghost** [comment]
Bokeh, just like Wikipedia says lol

**Comment by ghost** [comment]
Then fix it in `README.md`

- https://github.com/cgvirus/Olive-Editor-Community-Effects/blob/master/README.md

**Comment by cgvirus** [comment]
Fixed Thanks
